### PR TITLE
add '9-2020-q2-update'

### PR DESCRIPTION
**Pull request by gretel**
this adds the recent release. regards

### CODE REVIEW

**Comment by fiam** [comment]
Hi @gretel. Thanks for your contribution. I'm merging it and creating a new patch release.

**Comment by gretel** [comment]
cool thanks.

**Comment by nerdCopter** [comment]
* thank you both very much. 
* it does fail. 
* unconfirmed, but i think for success/consistency it needs to be:
`src/gcc.ts:2`  `  '9-2020-q2':`  rather than   `'9-2020-q2-update':`

and

```
  with:
    release: 9-2020-q2
```

failed run:
```
Run fiam/arm-none-eabi-gcc@v1
  with:
    release: 9-2020-q2-update
  env:
    PULL_NUMBER: 282
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
(node:2716) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
##[error]invalid version 9-2020-q2-update. Available: 9-2019-q4,8-2019-q3,8-2018-q4,7-2018-q2,7-2017-q4,6-2017-q2,6-2017-q1,6-2016-q4,5-2016-q3,5-2016-q2,5-2016-q1,5-2015-q4,4.9-2015-q3,4.9-2015-q2,4.9-2015-q1,4.9-2014-q4,4.8-2014-q3,4.8-2014-q2,4.8-2014-q1,4.7-2014-q2,4.8-2013-q4,4.7-2013-q3,4.7-2013-q2,4.7-2013-q1,4.7-2012-q4
```

**Comment by gretel** [comment]
but `9-2020-q2-update` is what they defined upstream https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

**Comment by nerdCopter** [comment]
agreed in the URL, but Fiam's source-code does not include `-major` or `-update` in the `with.release` definition `key`'s of `gcc.ts`

**Comment by gretel** [comment]
https://github.com/fiam/arm-none-eabi-gcc/blob/master/src/gcc.ts#L2
looks good to me? but the string is not showing up in the list of options shown on error.

**Comment by fiam** [comment]
@gretel @nerdCopter I've just fixed the key, it shouldn't include the update `-update` suffix. The PR was also missing the regeneration of the `dest/index.js` file. Both should be fixed in `v1.0.2`.

**Comment by gretel** [comment]
@fiam cool thanks. can you tag this release as `v1`? cause version pinning is kinda cumbersome.. regarfs

**Pull request merged**
